<a href="https://colab.research.google.com/github/Tbaraka/Supervised-ML/blob/main/w9datatransformation1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Upload the 'w9.xlsx' file
from google.colab import files
income=files.upload()

Saving incomedataset.xlsx to incomedataset.xlsx

In [3]:
# Load the 'w9.xlsx' Excel file into a pandas DataFrame and display its head
import pandas as pd
income=pd.read_excel('incomedataset.xlsx')
display(income.head())

,age,"workclass (eg. private, local-gov, never-worked…)",education,education-num,occupation,sex,income
0,39,State-gov,Bachelors,13,Adm-clerical,Male,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Exec-managerial,Male,<=50K
2,38,Private,HS-grad,9,Handlers-cleaners,Male,<=50K
3,53,Private,11th,7,Handlers-cleaners,Male,<=50K
4,28,Private,Bachelors,13,Prof-specialty,Female,<=50K

In [4]:
# Perform one-hot encoding on the 'income' DataFrame and display its head
e_income=pd.get_dummies(income,dtype=int)
display(e_income.head())

,age,education-num,"workclass (eg. private, local-gov, never-worked…)_ ?","workclass (eg. private, local-gov, never-worked…)_ Federal-gov","workclass (eg. private, local-gov, never-worked…)_ Local-gov","workclass (eg. private, local-gov, never-worked…)_ Never-worked","workclass (eg. private, local-gov, never-worked…)_ Private","workclass (eg. private, local-gov, never-worked…)_ Self-emp-inc","workclass (eg. private, local-gov, never-worked…)_ Self-emp-not-inc","workclass (eg. private, local-gov, never-worked…)_ State-gov",...,occupation_ Priv-house-serv,occupation_ Prof-specialty,occupation_ Protective-serv,occupation_ Sales,occupation_ Tech-support,occupation_ Transport-moving,sex_ Female,sex_ Male,income_ <=50K,income_ >50K
0,39,13,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,1,0
1,50,13,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,1,0
2,38,9,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,1,0
3,53,7,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,1,0
4,28,13,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,1,0,1,0

In [5]:
#deserializing
#Create 5 bins for the 'age' column and display them
import numpy as np
bins =np.linspace(max(e_income["age"]),min(e_income["age"]),5)#no of groupings
bins

array([90.  , 71.75, 53.5 , 35.25, 17.  ])

In [7]:
#Assign each 'age' value to a bin and create a new 'b_age' column
#binning or discretization. It categorizes continuous numerical data
e_income["b_age"]=np.digitize(e_income["age"],bins=bins)
#display(e_income)
print(e_income)

       age  education-num  \
0       39             13
1       50             13
2       38              9
3       53              7
4       28             13
...    ...            ...
32556   27             12
32557   40              9
32558   58              9
32559   22              9
32560   52              9

       workclass (eg. private, local-gov, never-worked…)_ ?  \
0                                                      0
1                                                      0
2                                                      0
3                                                      0
4                                                      0
...                                                  ...
32556                                                  0
32557                                                  0
32558                                                  0
32559                                                  0
32560                                                  0

       workclass (eg. private, local-gov, never-worked…)_ Federal-gov  \
0                                                      0
1                                                      0
2                                                      0
3                                                      0
4                                                      0
...                                                  ...
32556                                                  0
32557                                                  0
32558                                                  0
32559                                                  0
32560                                                  0

       workclass (eg. private, local-gov, never-worked…)_ Local-gov  \
0                                                      0
1                                                      0
2                                                      0
3                                                      0
4                                                      0
...                                                  ...
32556                                                  0
32557                                                  0
32558                                                  0
32559                                                  0
32560                                                  0

       workclass (eg. private, local-gov, never-worked…)_ Never-worked  \
0                                                      0
1                                                      0
2                                                      0
3                                                      0
4                                                      0
...                                                  ...
32556                                                  0
32557                                                  0
32558                                                  0
32559                                                  0
32560                                                  0

       workclass (eg. private, local-gov, never-worked…)_ Private  \
0                                                      0
1                                                      0
2                                                      1
3                                                      1
4                                                      1
...                                                  ...
32556                                                  1
32557                                                  1
32558                                                  1
32559                                                  1
32560                                                  0

       workclass (eg. private, local-gov, never-worked…)_ Self-emp-inc  \
0                                                      0
1                                                      0
2                                                      0
3                                                      0
4                                                      0
...                                                  ...
32556                                                  0
32557                                                  0
32558                                                  0
32559                                                  0
32560                                                  1

       workclass (eg. private, local-gov, never-worked…)_ Self-emp-not-inc  \
0                                                      0
1                                                      1
2                                                      0
3                                                      0
4                                                      0
...                                                  ...
32556                                                  0
32557                                                  0
32558                                                  0
32559                                                  0
32560                                                  0

       workclass (eg. private, local-gov, never-worked…)_ State-gov  ...  \
0                                                      1             ...
1                                                      0             ...
2                                                      0             ...
3                                                      0             ...
4                                                      0             ...
...                                                  ...             ...
32556                                                  0             ...
32557                                                  0             ...
32558                                                  0             ...
32559                                                  0             ...
32560                                                  0             ...

       occupation_ Prof-specialty  occupation_ Protective-serv  \
0                               0                            0
1                               0                            0
2                               0                            0
3                               0                            0
4                               1                            0
...                           ...                          ...
32556                           0                            0
32557                           0                            0
32558                           0                            0
32559                           0                            0
32560                           0                            0

       occupation_ Sales  occupation_ Tech-support  \
0                      0                         0
1                      0                         0
2                      0                         0
3                      0                         0
4                      0                         0
...                  ...                       ...
32556                  0                         1
32557                  0                         0
32558                  0                         0
32559                  0                         0
32560                  0                         0

       occupation_ Transport-moving  sex_ Female  sex_ Male  income_ <=50K  \
0                                 0            0          1              1
1                                 0            0          1              1
2                                 0            0          1              1
3                                 0            0          1              1
4                                 0            1          0              1
...                             ...          ...        ...            ...
32556                             0            1          0              1
32557                             0            0          1              0
32558                             0            1          0              1
32559                             0            0          1              1
32560                             0            1          0              0

       income_ >50K  b_age
0                 0      3
1                 0      3
2                 0      3
3                 0      3
4                 0      4
...             ...    ...
32556             0      4
32557             1      3
32558             0      2
32559             0      4
32560             1      3

[32561 rows x 47 columns]

In [15]:
e_income=e_income.drop(columns="age")

KeyError: "['age'] not found in axis"

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Drop columns that are mostly NaN (the 'Unnamed' columns)
X = e_income.drop(columns=["income_ <=50K", "income_ >50K"])
y = e_income["income_ <=50K"]

X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0)

#train the data
liReg=LogisticRegression().fit(X_train,y_train)#specifies which algorithm to use and trains
print("Training accuracy" ,liReg.score(X_train,y_train) )
print("test accuracy" ,liReg.score(X_test,y_test) )

Training accuracy 0.8079033579033579
test accuracy 0.8043237931458052

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
#is decritization and encodinf enough

In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

X = e_income.drop(columns=["income_ <=50K", "income_ >50K"])
y = e_income["income_ <=50K"]
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0)


# Initialize and train the Decision Tree Classifier
dt_classifier = DecisionTreeClassifier()
dt_classifier.fit(X_train, y_train)

# Print the training and test accuracy for the Decision Tree model
print("Decision Tree Training accuracy:", dt_classifier.score(X_train, y_train))
print("Decision Tree Test accuracy:", dt_classifier.score(X_test, y_test))

Decision Tree Training accuracy: 0.8306715806715806
Decision Tree Test accuracy: 0.7990418867461